runtime: nodejs
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

#instance_class: F1
env_variables:
  DB_USER: postgres
  DB_PASS: database
  DB_NAME: sistemasdistribuidosbooks
  #DB_PORT : 5432
  #DB_HOST : localhost
  INSTANCE_CONNECTION_NAME: practicasistemas:us-central1:databaseapi

beta_settings:
  cloud_sql_instances: practicasistemas:us-central1:databaseapi
  
#network: {}

  